// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";
import * as BetterReactMathjax from "better-react-mathjax";

var Context = {};

var Content = {};

function inline(str) {
  return "\\(" + str + "\\)";
}

function display(str) {
  return "\\[" + str + "\\]";
}

function Mathjax(props) {
  var __dynamic = props.dynamic;
  var __inline = props.inline;
  var inline = __inline !== undefined ? __inline : false;
  var dynamic = __dynamic !== undefined ? __dynamic : false;
  return JsxRuntime.jsx(BetterReactMathjax.MathJax, {
              children: props.children,
              inline: inline,
              dynamic: dynamic
            });
}

var make = Mathjax;

export {
  Context ,
  Content ,
  inline ,
  display ,
  make ,
}
/* react/jsx-runtime Not a pure module */
