// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function map(xs, fn) {
  return xs.map(fn);
}

function mapi(xs, fn) {
  return xs.map(fn);
}

function mapfor(i, fn) {
  return Core__Array.fromInitializer(i, fn);
}

export {
  map ,
  mapi ,
  mapfor ,
}
/* No side effect */
