// Generated by ReScript, PLEASE EDIT WITH CARE


function Combinator(InParser, OutParser) {
  return {};
}

var Pipe = {};

function ParserMethods(Parser) {
  return {};
}

var IntParser = {};

var IntMethods = {};

function Result(Parser) {
  return {};
}

export {
  Combinator ,
  Pipe ,
  ParserMethods ,
  IntParser ,
  IntMethods ,
  Result ,
}
/* No side effect */
