FROM node:18-alpine

ARG CLIENT_PORT
ENV CLIENT_PORT ${CLIENT_PORT}

WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
COPY ./next.config.mjs .
COPY ./tailwind.config.js .
COPY ./postcss.config.mjs .
#COPY ./public/static .
COPY ./rescript.json .
COPY ./jsconfig.json .

RUN yarn
CMD yarn dev ${CLIENT_PORT}
