services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        CLIENT_PORT: 3000
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    volumes:
      - ./src:/app/src
      - ./lib:/app/lib
    tty: true
