// Generated by ReScript, PLEASE EDIT WITH CARE

import * as TruthTable from "./components/TruthTable.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function $$default() {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(TruthTable.make, {})
            });
}

export {
  $$default as default,
}
/* TruthTable Not a pure module */
