'use client';
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as TableInput from "./components/TableInput.res.mjs";
import * as ExpressionInput from "./components/ExpressionInput.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Index$InputSelector(props) {
  var setSpecType = props.setSpecType;
  var buttonStyle = "py-2 px-2 border rounded-lg";
  var inactiveButtonStyle = "";
  var activeButtonStyle = "bg-accent text-white font-bold";
  var match;
  match = props.specType === "TruthTable" ? [
      inactiveButtonStyle,
      activeButtonStyle
    ] : [
      activeButtonStyle,
      inactiveButtonStyle
    ];
  var onClickExpressionButton = function (param) {
    setSpecType(function (param) {
          return "Expression";
        });
  };
  var onClickTruthTableButton = function (param) {
    setSpecType(function (param) {
          return "TruthTable";
        });
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Input method",
                              className: "font-bold py-2"
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Expression",
                              className: buttonStyle + " " + match[0],
                              onClick: onClickExpressionButton
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Truth table",
                              className: buttonStyle + " " + match[1],
                              onClick: onClickTruthTableButton
                            })
                      ],
                      className: "flex flex-row gap-4 align-items-center"
                    }),
                JsxRuntime.jsx("hr", {
                      className: "h-px border-1"
                    })
              ],
              className: "flex flex-col gap-4"
            });
}

function Index(props) {
  var match = React.useState(function () {
        return "Expression";
      });
  var specType = match[0];
  var tmp;
  tmp = specType === "TruthTable" ? JsxRuntime.jsx(TableInput.make, {}) : JsxRuntime.jsx(ExpressionInput.make, {});
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: "This is a tool for experimenting with the four-valued Belnap system of logic. To get started, choose a way of specifying a function in Belnap logic below."
                    }),
                JsxRuntime.jsx(Index$InputSelector, {
                      specType: specType,
                      setSpecType: match[1]
                    }),
                tmp
              ],
              className: "flex flex-col gap-4"
            });
}

var make = Index;

export {
  make ,
}
/* react Not a pure module */
