// Generated by ReScript, PLEASE EDIT WITH CARE

import * as MoreReact from "./bindings/MoreReact.res.mjs";
import * as Expression from "./theory/Expression.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Index$P(props) {
  return JsxRuntime.jsx("p", {
              children: props.children,
              className: "mb-2"
            });
}

function $$default() {
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("h1", {
                      children: "What is this about?",
                      className: "text-3xl font-semibold"
                    }),
                JsxRuntime.jsx(Index$P, {
                      children: " This is a simple template for a Next\n      project using ReScript & TailwindCSS."
                    }),
                JsxRuntime.jsx("h2", {
                      children: "Quick Start",
                      className: "text-2xl font-semibold mt-5"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: MoreReact.map(Expression.strings_of_table(Expression.test_table), (function (row) {
                                      return JsxRuntime.jsx("div", {
                                                  children: row,
                                                  className: "font-mono"
                                                });
                                    }))
                            }),
                        JsxRuntime.jsx("div", {
                              children: MoreReact.map(Expression.strings_of_table(Expression.test_falsy_table), (function (row) {
                                      return JsxRuntime.jsx("div", {
                                                  children: row,
                                                  className: "font-mono"
                                                });
                                    }))
                            }),
                        JsxRuntime.jsx("div", {
                              children: MoreReact.map(Expression.strings_of_table(Expression.test_truthy_table), (function (row) {
                                      return JsxRuntime.jsx("div", {
                                                  children: row,
                                                  className: "font-mono"
                                                });
                                    }))
                            }),
                        JsxRuntime.jsx("div", {
                              children: Expression.string_of_expression(Expression.test_exp),
                              className: "font-mono"
                            })
                      ],
                      className: "flex flex-col gap-5"
                    })
              ]
            });
}

export {
  $$default as default,
}
/* Expression Not a pure module */
