// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function MainLayout$TopBar(props) {
  return JsxRuntime.jsx("nav", {
              children: JsxRuntime.jsx("div", {
                    children: "Belnap tools",
                    className: "text-white text-lg font-bold"
                  }),
              className: "w-full p-2 h-12 flex border-b border-gray-200 justify-between items-center text-sm bg-accent"
            });
}

function MainLayout(props) {
  var minWidth = {
    minWidth: "20rem"
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx(MainLayout$TopBar, {}),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("main", {
                            children: props.children,
                            className: "mt-4 mx-4"
                          }),
                      className: "max-w-5xl w-full lg:w-3/4 text-gray-900 font-base align-center"
                    })
              ],
              className: "flex flex-col items-center",
              style: minWidth
            });
}

var make = MainLayout;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
