// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";

function concatStrings(ss, delimOpt) {
  var delim = delimOpt !== undefined ? delimOpt : ", ";
  return Core__Array.reduce(ss, "", (function (acc, cur) {
                if (acc === "") {
                  return cur;
                } else {
                  return acc + delim + cur;
                }
              }));
}

export {
  concatStrings ,
}
/* No side effect */
